Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026







Var
// Seção de Declarações das variáveis
n3, ant, suc: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite um numero: ")
   leia(n3)

   ant <- n3 - 1
   suc <- n3 + 1

   escreva("Antecessor: ", ant)
   escreva("Sucessor: ", suc)


Fimalgoritmo