Algoritmo "ex5"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026

Var
nota, n1, n2: real

Inicio
Escreval("Digite sua nota: ")
Leia(nota)
Escreval("digite sua segunda nota: ")
leia(n1)
Escreval("digite sua terceira nota: ")
leia(n2)
real(nota + n1 + n2)/3
escreval("sua media final:", nota)
Fimalgoritmo

// Seção de Comandos, procedimento, funções, operadores, etc... 
