Algoritmo "ex7"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
resto, divisao: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("digite um numero:")
leia(resto)
divisao<-resto mod 2
escreval("o resto é:", divisao)

Fimalgoritmo