Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026

Var
   base, altura, area: real

Inicio
   Escreval("Digite a base do retangulo: ")
   Leia(base)

   Escreval("Digite a altura do retangulo: ")
   Leia(altura)

   area <- base * altura

   Escreval("A área do retangulo e: ", area)

Fimalgoritmo

// Seção de Comandos, procedimento, funções, operadores, etc... 
