Algoritmo "ex22"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/02/2026
var
   n, i, soma: inteiro

inicio
   escreva("Digite um numero inteiro N: ")
   leia(n)

   soma <- 0
   i <- 1

   enquanto (i <= n) faca
      soma <- soma + i
      i <- i + 1
   fimenquanto

   escreval("A soma de 1 ate ", n, " é ", soma)

Fimalgoritmo